CATEGORIES_MAP = {
    "groceries": "Продукти",
    "transport": "Транспорт",
    "entertainment": "Розваги",
    "healthcare": "Здоров'я",
    "clothing": "Одяг",
    "cafe": "Кафе",
    "connection": "Зв'язок",
    "shopping": "Покупки",
    "home": "Дім і сад",
    "financial": "Фінанси",
    "education": "Освіта",
    "professional": "Професійні послуги",
    "beauty": "Краса",
    "government": "Державні послуги",
    "utilities": "Комунальні послуги",
    "hotel": "Готелі",
    "digital": "Цифрові товари",
    "other": "Інше",
    "all": "Усі категорії"
}