services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expenses_server
    command: python main.py
    environment:
      - FLASK_APP=main.py
      - DATABASE_URL=${DATABASE_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - BROKER_URL=${BROKER_URL}
      - FERNET_KEY=${FERNET_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - redis
    ports:
      - "5000:5000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: python run_worker.py
    environment:
      - FLASK_APP=main.py
      - DATABASE_URL=${DATABASE_URL}
      - BROKER_URL=${BROKER_URL}
    depends_on:
      - redis
      - server