services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "no", "--save", ""]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expenses_server
    command: gunicorn -w 4 -b 0.0.0.0:5000 main:app
    environment:
      - FLASK_APP=main.py
      - DATABASE_URL=${DATABASE_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - BROKER_URL=${BROKER_URL}
      - FERNET_KEY=${FERNET_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - redis
    ports:
      - "5000:5000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A run_worker.celery_app worker --loglevel=info --concurrency=2
    environment:
      - FLASK_APP=main.py
      - DATABASE_URL=${DATABASE_URL}
      - BROKER_URL=${BROKER_URL}
    depends_on:
      - redis
      - server